kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager-sample
  namespace: 3scale
spec:
  wildcardDomain: apps.XXX
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: ocs-external-storagecluster-cephfs
  apicast:
    productionSpec:
# Configuracao de teste pois estava dando crashloopback
#      configurationLoader: lazy
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
    stagingSpec:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m          